// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "en-US";

export type Locales = "en-US" | "fr-FR";

export type Translation = {
    /**
     * English
     */
    language: string;
    /**
     * United States
     */
    country: string;
    audio: {
        manager: {
            /**
             * reduce in conversations
             */
            reduce: string;
        };
        /**
         * Audio message
         */
        message: string;
    };
    camera: {
        enable: {
            /**
             * Turn on your camera and microphone
             */
            title: string;
            /**
             * Let's go!
             */
            start: string;
        };
        help: {
            /**
             * Camera / Microphone access needed
             */
            title: string;
            /**
             * Permission denied
             */
            permissionDenied: string;
            /**
             * You must allow camera and microphone access in your browser.
             */
            content: string;
            /**
             * Please click the "Remember this decision" checkbox, if you don't want Firefox to keep asking you the authorization.
             */
            firefoxContent: string;
            /**
             * Refresh
             */
            refresh: string;
            /**
             * Continue without webcam
             */
            continue: string;
        };
        my: {
            /**
             * Silent zone
             */
            silentZone: string;
        };
    };
    chat: {
        /**
         * Here is your chat history:
         */
        intro: string;
        /**
         * Enter your message...
         */
        enter: string;
        menu: {
            /**
             * Visit card
             */
            visitCard: string;
            /**
             * Add friend
             */
            addFriend: string;
        };
    };
    companion: {
        select: {
            /**
             * Select your companion
             */
            title: string;
            /**
             * No companion
             */
            any: string;
            /**
             * Continue
             */
            continue: string;
        };
    };
    woka: {
        customWoka: {
            /**
             * Customize your WOKA
             */
            title: string;
            navigation: {
                /**
                 * Return
                 */
                return: string;
                /**
                 * Back
                 */
                back: string;
                /**
                 * Finish
                 */
                finish: string;
                /**
                 * Next
                 */
                next: string;
            };
        };
        selectWoka: {
            /**
             * Select your WOKA
             */
            title: string;
            /**
             * Continue
             */
            continue: string;
            /**
             * Customize your WOKA
             */
            customize: string;
        };
    };
    error: {
        accessLink: {
            /**
             * Access link incorrect
             */
            title: string;
            /**
             * Could not find map. Please check your access link.
             */
            subTitle: string;
            /**
             * If you want more information, you may contact administrator or contact us at: hello@workadventu.re
             */
            details: string;
        };
        connectionRejected: {
            /**
             * Connection rejected
             */
            title: string;
            /**
             * You cannot join the World. Try again later {error}.
             * @param {unknown} error
             */
            subTitle: RequiredParams1<"error">;
            /**
             * If you want more information, you may contact administrator or contact us at: hello@workadventu.re
             */
            details: string;
        };
        connectionRetry: {
            /**
             * Unable to connect to WorkAdventure. Are you connected to internet?
             */
            unableConnect: string;
        };
        /**
         * Error
         */
        error: string;
    };
    follow: {
        interactStatus: {
            /**
             * Following {leader}
             * @param {unknown} leader
             */
            following: RequiredParams1<"leader">;
            /**
             * Waiting for followers confirmation
             */
            waitingFollowers: string;
            followed: {
                /**
                 * {follower} is following you
                 * @param {unknown} follower
                 */
                one: RequiredParams1<"follower">;
                /**
                 * {firstFollower} and {secondFollower} are following you
                 * @param {unknown} firstFollower
                 * @param {unknown} secondFollower
                 */
                two: RequiredParams2<"firstFollower", "secondFollower">;
                /**
                 * {followers} and {lastFollower} are following you
                 * @param {unknown} followers
                 * @param {unknown} lastFollower
                 */
                many: RequiredParams2<"followers", "lastFollower">;
            };
        };
        interactMenu: {
            title: {
                /**
                 * Interaction
                 */
                interact: string;
                /**
                 * Do you want to follow {leader}?
                 * @param {unknown} leader
                 */
                follow: RequiredParams1<"leader">;
            };
            stop: {
                /**
                 * Do you want to stop leading the way?
                 */
                leader: string;
                /**
                 * Do you want to stop following {leader}?
                 * @param {unknown} leader
                 */
                follower: RequiredParams1<"leader">;
            };
            /**
             * Yes
             */
            yes: string;
            /**
             * No
             */
            no: string;
        };
    };
    login: {
        input: {
            name: {
                /**
                 * Enter your name
                 */
                placeholder: string;
                /**
                 * The name is empty
                 */
                empty: string;
            };
        };
        /**
         * By continuing, you are agreeing our <a href="https://workadventu.re/terms-of-use" target="_blank">terms of use</a>, <a href="https://workadventu.re/privacy-policy" target="_blank">privacy policy</a> and <a href="https://workadventu.re/cookie-policy" target="_blank">cookie policy</a>.
         */
        terms: string;
        /**
         * Continue
         */
        continue: string;
    };
    menu: {
        /**
         * Menu
         */
        title: string;
        icon: {
            open: {
                /**
                 * Open menu
                 */
                menu: string;
                /**
                 * Show invite
                 */
                invite: string;
                /**
                 * Register
                 */
                register: string;
                /**
                 * Open chat
                 */
                chat: string;
            };
        };
        visitCard: {
            /**
             * Close
             */
            close: string;
        };
        profile: {
            edit: {
                /**
                 * Edit your name
                 */
                name: string;
                /**
                 * Edit your WOKA
                 */
                woka: string;
                /**
                 * Edit your companion
                 */
                companion: string;
                /**
                 * Edit your camera
                 */
                camera: string;
            };
            /**
             * Sign in
             */
            login: string;
            /**
             * Log out
             */
            logout: string;
        };
        settings: {
            gameQuality: {
                /**
                 * Game quality
                 */
                title: string;
                short: {
                    /**
                     * High (120 fps)
                     */
                    high: string;
                    /**
                     * Medium (60 fps)
                     */
                    medium: string;
                    /**
                     * Minimum (40 fps)
                     */
                    minimum: string;
                    /**
                     * Small (20 fps)
                     */
                    small: string;
                };
                long: {
                    /**
                     * High video quality (120 fps)
                     */
                    high: string;
                    /**
                     * Medium video quality (60 fps, recommended)
                     */
                    medium: string;
                    /**
                     * Minimum video quality (40 fps)
                     */
                    minimum: string;
                    /**
                     * Small video quality (20 fps)
                     */
                    small: string;
                };
            };
            videoQuality: {
                /**
                 * Video quality
                 */
                title: string;
                short: {
                    /**
                     * High (30 fps)
                     */
                    high: string;
                    /**
                     * Medium (20 fps)
                     */
                    medium: string;
                    /**
                     * Minimum (10 fps)
                     */
                    minimum: string;
                    /**
                     * Small (5 fps)
                     */
                    small: string;
                };
                long: {
                    /**
                     * High video quality (30 fps)
                     */
                    high: string;
                    /**
                     * Medium video quality (20 fps, recommended)
                     */
                    medium: string;
                    /**
                     * Minimum video quality (10 fps)
                     */
                    minimum: string;
                    /**
                     * Small video quality (5 fps)
                     */
                    small: string;
                };
            };
            language: {
                /**
                 * Language
                 */
                title: string;
            };
            save: {
                /**
                 * (Saving these settings will restart the game)
                 */
                warning: string;
                /**
                 * Save
                 */
                button: string;
            };
            /**
             * Fullscreen
             */
            fullscreen: string;
            /**
             * Notifications
             */
            notifications: string;
            /**
             * Always ask before opening websites and Jitsi Meet rooms
             */
            cowebsiteTrigger: string;
            /**
             * Ignore requests to follow other users
             */
            ignoreFollowRequest: string;
        };
        invite: {
            /**
             * Share the link of the room!
             */
            description: string;
            /**
             * Copy
             */
            copy: string;
            /**
             * Share
             */
            share: string;
        };
        globalMessage: {
            /**
             * Text
             */
            text: string;
            /**
             * Audio
             */
            audio: string;
            /**
             * Broadcast to all rooms of the world
             */
            warning: string;
            /**
             * Enter your message here...
             */
            enter: string;
            /**
             * Send
             */
            send: string;
        };
        globalAudio: {
            /**
             * Upload a file
             */
            uploadInfo: string;
            /**
             * No file selected. You need to upload a file before sending it.
             */
            error: string;
        };
        contact: {
            gettingStarted: {
                /**
                 * Getting started
                 */
                title: string;
                /**
                 * WorkAdventure allows you to create an online space to communicate spontaneously with others. And it all starts with creating your own space. Choose from a large selection of prefabricated maps by our team.
                 */
                description: string;
            };
            createMap: {
                /**
                 * Create your map
                 */
                title: string;
                /**
                 * You can also create your own custom map by following the step of the documentation.
                 */
                description: string;
            };
        };
        about: {
            /**
             * Information on the map
             */
            mapInfo: string;
            /**
             * link to this map
             */
            mapLink: string;
            copyrights: {
                map: {
                    /**
                     * Copyrights of the map
                     */
                    title: string;
                    /**
                     * The map creator did not declare a copyright for the map.
                     */
                    empty: string;
                };
                tileset: {
                    /**
                     * Copyrights of the tilesets
                     */
                    title: string;
                    /**
                     * The map creator did not declare a copyright for the tilesets. This doesn't mean that those tilesets have no license.
                     */
                    empty: string;
                };
                audio: {
                    /**
                     * Copyrights of audio files
                     */
                    title: string;
                    /**
                     * The map creator did not declare a copyright for audio files. This doesn't mean that those audio files have no license.
                     */
                    empty: string;
                };
            };
        };
        sub: {
            /**
             * Profile
             */
            profile: string;
            /**
             * Settings
             */
            settings: string;
            /**
             * Invite
             */
            invite: string;
            /**
             * Credit
             */
            credit: string;
            /**
             * Global Messages
             */
            globalMessages: string;
            /**
             * Contact
             */
            contact: string;
        };
    };
    report: {
        block: {
            /**
             * Block
             */
            title: string;
            /**
             * Block any communication from and to {userName}. This can be reverted.
             * @param {unknown} userName
             */
            content: RequiredParams1<"userName">;
            /**
             * Unblock this user
             */
            unblock: string;
            /**
             * Block this user
             */
            block: string;
        };
        /**
         * Report
         */
        title: string;
        /**
         * Send a report message to the administrators of this room. They may later ban this user.
         */
        content: string;
        message: {
            /**
             * Your message:
             */
            title: string;
            /**
             * Report message cannot to be empty.
             */
            empty: string;
        };
        /**
         * Report this user
         */
        submit: string;
        moderate: {
            /**
             * Moderate {userName}
             * @param {unknown} userName
             */
            title: RequiredParams1<"userName">;
            /**
             * Block
             */
            block: string;
            /**
             * Report
             */
            report: string;
            /**
             * ERROR : There is no action selected.
             */
            noSelect: string;
        };
    };
    warning: {
        /**
         * Warning!
         */
        title: string;
        /**
         * This world is close to its limit!. You can upgrade its capacity <a href={upgradeLink} target="_blank">here</a>
         * @param {unknown} upgradeLink
         */
        content: RequiredParams1<"upgradeLink">;
        /**
         * This world is close to its limit!
         */
        limit: string;
        accessDenied: {
            /**
             * Camera access denied. Click here and check your browser permissions.
             */
            camera: string;
            /**
             * Screen sharing denied. Click here and check your browser permissions.
             */
            screenSharing: string;
        };
        /**
         * Important message
         */
        importantMessage: string;
        /**
         * Connection lost. Reconnecting...
         */
        connectionLost: string;
    };
};

export type TranslationFunctions = {
    /**
     * English
     */
    language: () => LocalizedString;
    /**
     * United States
     */
    country: () => LocalizedString;
    audio: {
        manager: {
            /**
             * reduce in conversations
             */
            reduce: () => LocalizedString;
        };
        /**
         * Audio message
         */
        message: () => LocalizedString;
    };
    camera: {
        enable: {
            /**
             * Turn on your camera and microphone
             */
            title: () => LocalizedString;
            /**
             * Let's go!
             */
            start: () => LocalizedString;
        };
        help: {
            /**
             * Camera / Microphone access needed
             */
            title: () => LocalizedString;
            /**
             * Permission denied
             */
            permissionDenied: () => LocalizedString;
            /**
             * You must allow camera and microphone access in your browser.
             */
            content: () => LocalizedString;
            /**
             * Please click the "Remember this decision" checkbox, if you don't want Firefox to keep asking you the authorization.
             */
            firefoxContent: () => LocalizedString;
            /**
             * Refresh
             */
            refresh: () => LocalizedString;
            /**
             * Continue without webcam
             */
            continue: () => LocalizedString;
        };
        my: {
            /**
             * Silent zone
             */
            silentZone: () => LocalizedString;
        };
    };
    chat: {
        /**
         * Here is your chat history:
         */
        intro: () => LocalizedString;
        /**
         * Enter your message...
         */
        enter: () => LocalizedString;
        menu: {
            /**
             * Visit card
             */
            visitCard: () => LocalizedString;
            /**
             * Add friend
             */
            addFriend: () => LocalizedString;
        };
    };
    companion: {
        select: {
            /**
             * Select your companion
             */
            title: () => LocalizedString;
            /**
             * No companion
             */
            any: () => LocalizedString;
            /**
             * Continue
             */
            continue: () => LocalizedString;
        };
    };
    woka: {
        customWoka: {
            /**
             * Customize your WOKA
             */
            title: () => LocalizedString;
            navigation: {
                /**
                 * Return
                 */
                return: () => LocalizedString;
                /**
                 * Back
                 */
                back: () => LocalizedString;
                /**
                 * Finish
                 */
                finish: () => LocalizedString;
                /**
                 * Next
                 */
                next: () => LocalizedString;
            };
        };
        selectWoka: {
            /**
             * Select your WOKA
             */
            title: () => LocalizedString;
            /**
             * Continue
             */
            continue: () => LocalizedString;
            /**
             * Customize your WOKA
             */
            customize: () => LocalizedString;
        };
    };
    error: {
        accessLink: {
            /**
             * Access link incorrect
             */
            title: () => LocalizedString;
            /**
             * Could not find map. Please check your access link.
             */
            subTitle: () => LocalizedString;
            /**
             * If you want more information, you may contact administrator or contact us at: hello@workadventu.re
             */
            details: () => LocalizedString;
        };
        connectionRejected: {
            /**
             * Connection rejected
             */
            title: () => LocalizedString;
            /**
             * You cannot join the World. Try again later {error}.
             */
            subTitle: (arg: { error: unknown }) => LocalizedString;
            /**
             * If you want more information, you may contact administrator or contact us at: hello@workadventu.re
             */
            details: () => LocalizedString;
        };
        connectionRetry: {
            /**
             * Unable to connect to WorkAdventure. Are you connected to internet?
             */
            unableConnect: () => LocalizedString;
        };
        /**
         * Error
         */
        error: () => LocalizedString;
    };
    follow: {
        interactStatus: {
            /**
             * Following {leader}
             */
            following: (arg: { leader: unknown }) => LocalizedString;
            /**
             * Waiting for followers confirmation
             */
            waitingFollowers: () => LocalizedString;
            followed: {
                /**
                 * {follower} is following you
                 */
                one: (arg: { follower: unknown }) => LocalizedString;
                /**
                 * {firstFollower} and {secondFollower} are following you
                 */
                two: (arg: { firstFollower: unknown; secondFollower: unknown }) => LocalizedString;
                /**
                 * {followers} and {lastFollower} are following you
                 */
                many: (arg: { followers: unknown; lastFollower: unknown }) => LocalizedString;
            };
        };
        interactMenu: {
            title: {
                /**
                 * Interaction
                 */
                interact: () => LocalizedString;
                /**
                 * Do you want to follow {leader}?
                 */
                follow: (arg: { leader: unknown }) => LocalizedString;
            };
            stop: {
                /**
                 * Do you want to stop leading the way?
                 */
                leader: () => LocalizedString;
                /**
                 * Do you want to stop following {leader}?
                 */
                follower: (arg: { leader: unknown }) => LocalizedString;
            };
            /**
             * Yes
             */
            yes: () => LocalizedString;
            /**
             * No
             */
            no: () => LocalizedString;
        };
    };
    login: {
        input: {
            name: {
                /**
                 * Enter your name
                 */
                placeholder: () => LocalizedString;
                /**
                 * The name is empty
                 */
                empty: () => LocalizedString;
            };
        };
        /**
         * By continuing, you are agreeing our <a href="https://workadventu.re/terms-of-use" target="_blank">terms of use</a>, <a href="https://workadventu.re/privacy-policy" target="_blank">privacy policy</a> and <a href="https://workadventu.re/cookie-policy" target="_blank">cookie policy</a>.
         */
        terms: () => LocalizedString;
        /**
         * Continue
         */
        continue: () => LocalizedString;
    };
    menu: {
        /**
         * Menu
         */
        title: () => LocalizedString;
        icon: {
            open: {
                /**
                 * Open menu
                 */
                menu: () => LocalizedString;
                /**
                 * Show invite
                 */
                invite: () => LocalizedString;
                /**
                 * Register
                 */
                register: () => LocalizedString;
                /**
                 * Open chat
                 */
                chat: () => LocalizedString;
            };
        };
        visitCard: {
            /**
             * Close
             */
            close: () => LocalizedString;
        };
        profile: {
            edit: {
                /**
                 * Edit your name
                 */
                name: () => LocalizedString;
                /**
                 * Edit your WOKA
                 */
                woka: () => LocalizedString;
                /**
                 * Edit your companion
                 */
                companion: () => LocalizedString;
                /**
                 * Edit your camera
                 */
                camera: () => LocalizedString;
            };
            /**
             * Sign in
             */
            login: () => LocalizedString;
            /**
             * Log out
             */
            logout: () => LocalizedString;
        };
        settings: {
            gameQuality: {
                /**
                 * Game quality
                 */
                title: () => LocalizedString;
                short: {
                    /**
                     * High (120 fps)
                     */
                    high: () => LocalizedString;
                    /**
                     * Medium (60 fps)
                     */
                    medium: () => LocalizedString;
                    /**
                     * Minimum (40 fps)
                     */
                    minimum: () => LocalizedString;
                    /**
                     * Small (20 fps)
                     */
                    small: () => LocalizedString;
                };
                long: {
                    /**
                     * High video quality (120 fps)
                     */
                    high: () => LocalizedString;
                    /**
                     * Medium video quality (60 fps, recommended)
                     */
                    medium: () => LocalizedString;
                    /**
                     * Minimum video quality (40 fps)
                     */
                    minimum: () => LocalizedString;
                    /**
                     * Small video quality (20 fps)
                     */
                    small: () => LocalizedString;
                };
            };
            videoQuality: {
                /**
                 * Video quality
                 */
                title: () => LocalizedString;
                short: {
                    /**
                     * High (30 fps)
                     */
                    high: () => LocalizedString;
                    /**
                     * Medium (20 fps)
                     */
                    medium: () => LocalizedString;
                    /**
                     * Minimum (10 fps)
                     */
                    minimum: () => LocalizedString;
                    /**
                     * Small (5 fps)
                     */
                    small: () => LocalizedString;
                };
                long: {
                    /**
                     * High video quality (30 fps)
                     */
                    high: () => LocalizedString;
                    /**
                     * Medium video quality (20 fps, recommended)
                     */
                    medium: () => LocalizedString;
                    /**
                     * Minimum video quality (10 fps)
                     */
                    minimum: () => LocalizedString;
                    /**
                     * Small video quality (5 fps)
                     */
                    small: () => LocalizedString;
                };
            };
            language: {
                /**
                 * Language
                 */
                title: () => LocalizedString;
            };
            save: {
                /**
                 * (Saving these settings will restart the game)
                 */
                warning: () => LocalizedString;
                /**
                 * Save
                 */
                button: () => LocalizedString;
            };
            /**
             * Fullscreen
             */
            fullscreen: () => LocalizedString;
            /**
             * Notifications
             */
            notifications: () => LocalizedString;
            /**
             * Always ask before opening websites and Jitsi Meet rooms
             */
            cowebsiteTrigger: () => LocalizedString;
            /**
             * Ignore requests to follow other users
             */
            ignoreFollowRequest: () => LocalizedString;
        };
        invite: {
            /**
             * Share the link of the room!
             */
            description: () => LocalizedString;
            /**
             * Copy
             */
            copy: () => LocalizedString;
            /**
             * Share
             */
            share: () => LocalizedString;
        };
        globalMessage: {
            /**
             * Text
             */
            text: () => LocalizedString;
            /**
             * Audio
             */
            audio: () => LocalizedString;
            /**
             * Broadcast to all rooms of the world
             */
            warning: () => LocalizedString;
            /**
             * Enter your message here...
             */
            enter: () => LocalizedString;
            /**
             * Send
             */
            send: () => LocalizedString;
        };
        globalAudio: {
            /**
             * Upload a file
             */
            uploadInfo: () => LocalizedString;
            /**
             * No file selected. You need to upload a file before sending it.
             */
            error: () => LocalizedString;
        };
        contact: {
            gettingStarted: {
                /**
                 * Getting started
                 */
                title: () => LocalizedString;
                /**
                 * WorkAdventure allows you to create an online space to communicate spontaneously with others. And it all starts with creating your own space. Choose from a large selection of prefabricated maps by our team.
                 */
                description: () => LocalizedString;
            };
            createMap: {
                /**
                 * Create your map
                 */
                title: () => LocalizedString;
                /**
                 * You can also create your own custom map by following the step of the documentation.
                 */
                description: () => LocalizedString;
            };
        };
        about: {
            /**
             * Information on the map
             */
            mapInfo: () => LocalizedString;
            /**
             * link to this map
             */
            mapLink: () => LocalizedString;
            copyrights: {
                map: {
                    /**
                     * Copyrights of the map
                     */
                    title: () => LocalizedString;
                    /**
                     * The map creator did not declare a copyright for the map.
                     */
                    empty: () => LocalizedString;
                };
                tileset: {
                    /**
                     * Copyrights of the tilesets
                     */
                    title: () => LocalizedString;
                    /**
                     * The map creator did not declare a copyright for the tilesets. This doesn't mean that those tilesets have no license.
                     */
                    empty: () => LocalizedString;
                };
                audio: {
                    /**
                     * Copyrights of audio files
                     */
                    title: () => LocalizedString;
                    /**
                     * The map creator did not declare a copyright for audio files. This doesn't mean that those audio files have no license.
                     */
                    empty: () => LocalizedString;
                };
            };
        };
        sub: {
            /**
             * Profile
             */
            profile: () => LocalizedString;
            /**
             * Settings
             */
            settings: () => LocalizedString;
            /**
             * Invite
             */
            invite: () => LocalizedString;
            /**
             * Credit
             */
            credit: () => LocalizedString;
            /**
             * Global Messages
             */
            globalMessages: () => LocalizedString;
            /**
             * Contact
             */
            contact: () => LocalizedString;
        };
    };
    report: {
        block: {
            /**
             * Block
             */
            title: () => LocalizedString;
            /**
             * Block any communication from and to {userName}. This can be reverted.
             */
            content: (arg: { userName: unknown }) => LocalizedString;
            /**
             * Unblock this user
             */
            unblock: () => LocalizedString;
            /**
             * Block this user
             */
            block: () => LocalizedString;
        };
        /**
         * Report
         */
        title: () => LocalizedString;
        /**
         * Send a report message to the administrators of this room. They may later ban this user.
         */
        content: () => LocalizedString;
        message: {
            /**
             * Your message:
             */
            title: () => LocalizedString;
            /**
             * Report message cannot to be empty.
             */
            empty: () => LocalizedString;
        };
        /**
         * Report this user
         */
        submit: () => LocalizedString;
        moderate: {
            /**
             * Moderate {userName}
             */
            title: (arg: { userName: unknown }) => LocalizedString;
            /**
             * Block
             */
            block: () => LocalizedString;
            /**
             * Report
             */
            report: () => LocalizedString;
            /**
             * ERROR : There is no action selected.
             */
            noSelect: () => LocalizedString;
        };
    };
    warning: {
        /**
         * Warning!
         */
        title: () => LocalizedString;
        /**
         * This world is close to its limit!. You can upgrade its capacity <a href={upgradeLink} target="_blank">here</a>
         */
        content: (arg: { upgradeLink: unknown }) => LocalizedString;
        /**
         * This world is close to its limit!
         */
        limit: () => LocalizedString;
        accessDenied: {
            /**
             * Camera access denied. Click here and check your browser permissions.
             */
            camera: () => LocalizedString;
            /**
             * Screen sharing denied. Click here and check your browser permissions.
             */
            screenSharing: () => LocalizedString;
        };
        /**
         * Important message
         */
        importantMessage: () => LocalizedString;
        /**
         * Connection lost. Reconnecting...
         */
        connectionLost: () => LocalizedString;
    };
};

export type Formatters = {};

type Param<P extends string> = `{${P}`;

type Params1<P1 extends string> = `${string}${Param<P1>}${string}`;

type Params2<P1 extends string, P2 extends string> = `${string}${Param<P1>}${string}${Param<P2>}${string}`;

type RequiredParams1<P1 extends string> = Params1<P1>;

type RequiredParams2<P1 extends string, P2 extends string> = Params2<P1, P2> | Params2<P2, P1>;
